
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/tools/cmake 3.30/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
